//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejecutable.ServiceReference3 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vehiculo", Namespace="http://schemas.datacontract.org/2004/07/Web.database")]
    [System.SerializableAttribute()]
    public partial class Vehiculo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConductorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EjesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdTipoVehiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ejecutable.ServiceReference3.TipoVehiculo TipoVehiculoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Conductor {
            get {
                return this.ConductorField;
            }
            set {
                if ((object.ReferenceEquals(this.ConductorField, value) != true)) {
                    this.ConductorField = value;
                    this.RaisePropertyChanged("Conductor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Ejes {
            get {
                return this.EjesField;
            }
            set {
                if ((this.EjesField.Equals(value) != true)) {
                    this.EjesField = value;
                    this.RaisePropertyChanged("Ejes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdTipoVehiculo {
            get {
                return this.IdTipoVehiculoField;
            }
            set {
                if ((this.IdTipoVehiculoField.Equals(value) != true)) {
                    this.IdTipoVehiculoField = value;
                    this.RaisePropertyChanged("IdTipoVehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Patente {
            get {
                return this.PatenteField;
            }
            set {
                if ((object.ReferenceEquals(this.PatenteField, value) != true)) {
                    this.PatenteField = value;
                    this.RaisePropertyChanged("Patente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ejecutable.ServiceReference3.TipoVehiculo TipoVehiculo {
            get {
                return this.TipoVehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoVehiculoField, value) != true)) {
                    this.TipoVehiculoField = value;
                    this.RaisePropertyChanged("TipoVehiculo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoVehiculo", Namespace="http://schemas.datacontract.org/2004/07/Web.database")]
    [System.SerializableAttribute()]
    public partial class TipoVehiculo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoVehiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoVehiculo {
            get {
                return this.IdTipoVehiculoField;
            }
            set {
                if ((this.IdTipoVehiculoField.Equals(value) != true)) {
                    this.IdTipoVehiculoField = value;
                    this.RaisePropertyChanged("IdTipoVehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IWCFVehiculo")]
    public interface IWCFVehiculo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFVehiculo/DoWork", ReplyAction="http://tempuri.org/IWCFVehiculo/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFVehiculo/DoWork", ReplyAction="http://tempuri.org/IWCFVehiculo/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFVehiculo/Listar", ReplyAction="http://tempuri.org/IWCFVehiculo/ListarResponse")]
        Ejecutable.ServiceReference3.Vehiculo[] Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFVehiculo/Listar", ReplyAction="http://tempuri.org/IWCFVehiculo/ListarResponse")]
        System.Threading.Tasks.Task<Ejecutable.ServiceReference3.Vehiculo[]> ListarAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFVehiculoChannel : Ejecutable.ServiceReference3.IWCFVehiculo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFVehiculoClient : System.ServiceModel.ClientBase<Ejecutable.ServiceReference3.IWCFVehiculo>, Ejecutable.ServiceReference3.IWCFVehiculo {
        
        public WCFVehiculoClient() {
        }
        
        public WCFVehiculoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFVehiculoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFVehiculoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFVehiculoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public Ejecutable.ServiceReference3.Vehiculo[] Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<Ejecutable.ServiceReference3.Vehiculo[]> ListarAsync() {
            return base.Channel.ListarAsync();
        }
    }
}
