//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejecutable.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vehiculo", Namespace="http://cocacola.cl/")]
    [System.SerializableAttribute()]
    public partial class Vehiculo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatenteField;
        
        private System.Nullable<int> IdTipoVehiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConductorField;
        
        private System.Nullable<int> EjesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ejecutable.ServiceReference1.TipoVehiculo TipoVehiculoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Patente {
            get {
                return this.PatenteField;
            }
            set {
                if ((object.ReferenceEquals(this.PatenteField, value) != true)) {
                    this.PatenteField = value;
                    this.RaisePropertyChanged("Patente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<int> IdTipoVehiculo {
            get {
                return this.IdTipoVehiculoField;
            }
            set {
                if ((this.IdTipoVehiculoField.Equals(value) != true)) {
                    this.IdTipoVehiculoField = value;
                    this.RaisePropertyChanged("IdTipoVehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Conductor {
            get {
                return this.ConductorField;
            }
            set {
                if ((object.ReferenceEquals(this.ConductorField, value) != true)) {
                    this.ConductorField = value;
                    this.RaisePropertyChanged("Conductor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> Ejes {
            get {
                return this.EjesField;
            }
            set {
                if ((this.EjesField.Equals(value) != true)) {
                    this.EjesField = value;
                    this.RaisePropertyChanged("Ejes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Ejecutable.ServiceReference1.TipoVehiculo TipoVehiculo {
            get {
                return this.TipoVehiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoVehiculoField, value) != true)) {
                    this.TipoVehiculoField = value;
                    this.RaisePropertyChanged("TipoVehiculo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoVehiculo", Namespace="http://cocacola.cl/")]
    [System.SerializableAttribute()]
    public partial class TipoVehiculo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdTipoVehiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdTipoVehiculo {
            get {
                return this.IdTipoVehiculoField;
            }
            set {
                if ((this.IdTipoVehiculoField.Equals(value) != true)) {
                    this.IdTipoVehiculoField = value;
                    this.RaisePropertyChanged("IdTipoVehiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cocacola.cl/", ConfigurationName="ServiceReference1.WebServiceVehiculoSoap")]
    public interface WebServiceVehiculoSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://cocacola.cl/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cocacola.cl/HelloWorld", ReplyAction="*")]
        Ejecutable.ServiceReference1.HelloWorldResponse HelloWorld(Ejecutable.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cocacola.cl/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Ejecutable.ServiceReference1.HelloWorldResponse> HelloWorldAsync(Ejecutable.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name ListarResult from namespace http://cocacola.cl/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cocacola.cl/Listar", ReplyAction="*")]
        Ejecutable.ServiceReference1.ListarResponse Listar(Ejecutable.ServiceReference1.ListarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cocacola.cl/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<Ejecutable.ServiceReference1.ListarResponse> ListarAsync(Ejecutable.ServiceReference1.ListarRequest request);
        
        // CODEGEN: Generating message contract since element name objeto from namespace http://cocacola.cl/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cocacola.cl/Insertar", ReplyAction="*")]
        Ejecutable.ServiceReference1.InsertarResponse Insertar(Ejecutable.ServiceReference1.InsertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cocacola.cl/Insertar", ReplyAction="*")]
        System.Threading.Tasks.Task<Ejecutable.ServiceReference1.InsertarResponse> InsertarAsync(Ejecutable.ServiceReference1.InsertarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://cocacola.cl/", Order=0)]
        public Ejecutable.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Ejecutable.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://cocacola.cl/", Order=0)]
        public Ejecutable.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Ejecutable.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cocacola.cl/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Listar", Namespace="http://cocacola.cl/", Order=0)]
        public Ejecutable.ServiceReference1.ListarRequestBody Body;
        
        public ListarRequest() {
        }
        
        public ListarRequest(Ejecutable.ServiceReference1.ListarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListarRequestBody {
        
        public ListarRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarResponse", Namespace="http://cocacola.cl/", Order=0)]
        public Ejecutable.ServiceReference1.ListarResponseBody Body;
        
        public ListarResponse() {
        }
        
        public ListarResponse(Ejecutable.ServiceReference1.ListarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cocacola.cl/")]
    public partial class ListarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Ejecutable.ServiceReference1.Vehiculo> ListarResult;
        
        public ListarResponseBody() {
        }
        
        public ListarResponseBody(System.Collections.Generic.List<Ejecutable.ServiceReference1.Vehiculo> ListarResult) {
            this.ListarResult = ListarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insertar", Namespace="http://cocacola.cl/", Order=0)]
        public Ejecutable.ServiceReference1.InsertarRequestBody Body;
        
        public InsertarRequest() {
        }
        
        public InsertarRequest(Ejecutable.ServiceReference1.InsertarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cocacola.cl/")]
    public partial class InsertarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ejecutable.ServiceReference1.Vehiculo objeto;
        
        public InsertarRequestBody() {
        }
        
        public InsertarRequestBody(Ejecutable.ServiceReference1.Vehiculo objeto) {
            this.objeto = objeto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarResponse", Namespace="http://cocacola.cl/", Order=0)]
        public Ejecutable.ServiceReference1.InsertarResponseBody Body;
        
        public InsertarResponse() {
        }
        
        public InsertarResponse(Ejecutable.ServiceReference1.InsertarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cocacola.cl/")]
    public partial class InsertarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertarResult;
        
        public InsertarResponseBody() {
        }
        
        public InsertarResponseBody(string InsertarResult) {
            this.InsertarResult = InsertarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceVehiculoSoapChannel : Ejecutable.ServiceReference1.WebServiceVehiculoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceVehiculoSoapClient : System.ServiceModel.ClientBase<Ejecutable.ServiceReference1.WebServiceVehiculoSoap>, Ejecutable.ServiceReference1.WebServiceVehiculoSoap {
        
        public WebServiceVehiculoSoapClient() {
        }
        
        public WebServiceVehiculoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceVehiculoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceVehiculoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceVehiculoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ejecutable.ServiceReference1.HelloWorldResponse Ejecutable.ServiceReference1.WebServiceVehiculoSoap.HelloWorld(Ejecutable.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Ejecutable.ServiceReference1.HelloWorldRequest inValue = new Ejecutable.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Ejecutable.ServiceReference1.HelloWorldRequestBody();
            Ejecutable.ServiceReference1.HelloWorldResponse retVal = ((Ejecutable.ServiceReference1.WebServiceVehiculoSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ejecutable.ServiceReference1.HelloWorldResponse> Ejecutable.ServiceReference1.WebServiceVehiculoSoap.HelloWorldAsync(Ejecutable.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ejecutable.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            Ejecutable.ServiceReference1.HelloWorldRequest inValue = new Ejecutable.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Ejecutable.ServiceReference1.HelloWorldRequestBody();
            return ((Ejecutable.ServiceReference1.WebServiceVehiculoSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ejecutable.ServiceReference1.ListarResponse Ejecutable.ServiceReference1.WebServiceVehiculoSoap.Listar(Ejecutable.ServiceReference1.ListarRequest request) {
            return base.Channel.Listar(request);
        }
        
        public System.Collections.Generic.List<Ejecutable.ServiceReference1.Vehiculo> Listar() {
            Ejecutable.ServiceReference1.ListarRequest inValue = new Ejecutable.ServiceReference1.ListarRequest();
            inValue.Body = new Ejecutable.ServiceReference1.ListarRequestBody();
            Ejecutable.ServiceReference1.ListarResponse retVal = ((Ejecutable.ServiceReference1.WebServiceVehiculoSoap)(this)).Listar(inValue);
            return retVal.Body.ListarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ejecutable.ServiceReference1.ListarResponse> Ejecutable.ServiceReference1.WebServiceVehiculoSoap.ListarAsync(Ejecutable.ServiceReference1.ListarRequest request) {
            return base.Channel.ListarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ejecutable.ServiceReference1.ListarResponse> ListarAsync() {
            Ejecutable.ServiceReference1.ListarRequest inValue = new Ejecutable.ServiceReference1.ListarRequest();
            inValue.Body = new Ejecutable.ServiceReference1.ListarRequestBody();
            return ((Ejecutable.ServiceReference1.WebServiceVehiculoSoap)(this)).ListarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ejecutable.ServiceReference1.InsertarResponse Ejecutable.ServiceReference1.WebServiceVehiculoSoap.Insertar(Ejecutable.ServiceReference1.InsertarRequest request) {
            return base.Channel.Insertar(request);
        }
        
        public string Insertar(Ejecutable.ServiceReference1.Vehiculo objeto) {
            Ejecutable.ServiceReference1.InsertarRequest inValue = new Ejecutable.ServiceReference1.InsertarRequest();
            inValue.Body = new Ejecutable.ServiceReference1.InsertarRequestBody();
            inValue.Body.objeto = objeto;
            Ejecutable.ServiceReference1.InsertarResponse retVal = ((Ejecutable.ServiceReference1.WebServiceVehiculoSoap)(this)).Insertar(inValue);
            return retVal.Body.InsertarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ejecutable.ServiceReference1.InsertarResponse> Ejecutable.ServiceReference1.WebServiceVehiculoSoap.InsertarAsync(Ejecutable.ServiceReference1.InsertarRequest request) {
            return base.Channel.InsertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ejecutable.ServiceReference1.InsertarResponse> InsertarAsync(Ejecutable.ServiceReference1.Vehiculo objeto) {
            Ejecutable.ServiceReference1.InsertarRequest inValue = new Ejecutable.ServiceReference1.InsertarRequest();
            inValue.Body = new Ejecutable.ServiceReference1.InsertarRequestBody();
            inValue.Body.objeto = objeto;
            return ((Ejecutable.ServiceReference1.WebServiceVehiculoSoap)(this)).InsertarAsync(inValue);
        }
    }
}
